export const ALAMO_STYLES = [
  {
    id: "control",
    label: "Current · control",
    shortLabel: "Control",
    rollingSrc: null,
    flatSrc: null,
    treeSrc: "/monterey-cypress.png",
    atmosphere: "control",
    rollingGroundOffset: 0,
    flatHorizon: 0,
    treeRootOffset: 0,
  },
  {
    id: "risograph",
    label: "Risograph print",
    shortLabel: "Risograph",
    rollingSrc: "/alamo-styles/risograph/rolling.png",
    flatSrc: "/alamo-styles/risograph/flat.png",
    treeSrc: "/alamo-styles/risograph/tree.png",
    atmosphere: "paper",
    rollingGroundOffset: 18,
    flatHorizon: 58.26,
    treeRootOffset: 3.71,
  },
  {
    id: "painterly-realism",
    label: "Restrained painterly",
    shortLabel: "Painterly",
    rollingSrc: "/alamo-styles/painterly-realism/rolling.png",
    flatSrc: "/alamo-styles/painterly-realism/flat.png",
    treeSrc: "/alamo-styles/painterly-realism/tree.png",
    atmosphere: "daylight",
    rollingGroundOffset: 15.05,
    flatHorizon: 69.05,
    treeRootOffset: 0.86,
  },
  {
    id: "ascii-terminal",
    label: "ASCII terminal garden",
    shortLabel: "ASCII",
    rollingSrc: "/alamo-styles/ascii-terminal/rolling.png",
    flatSrc: "/alamo-styles/ascii-terminal/flat.png",
    treeSrc: "/alamo-styles/ascii-terminal/tree.png",
    atmosphere: "terminal",
    rollingGroundOffset: 13.89,
    flatHorizon: 70.64,
    treeRootOffset: -2.59,
  },
  {
    id: "ascii-garden",
    label: "ASCII Garden · live prototype",
    shortLabel: "ASCII Garden",
    rollingSrc: null,
    flatSrc: null,
    treeSrc: "/monterey-cypress.png",
    atmosphere: "ascii-garden",
    rollingGroundOffset: 0,
    flatHorizon: 0,
    treeRootOffset: 0,
  },
  {
    id: "cut-paper",
    label: "Warm cut paper",
    shortLabel: "Cut paper",
    rollingSrc: "/alamo-styles/cut-paper/rolling.png",
    flatSrc: "/alamo-styles/cut-paper/flat.png",
    treeSrc: "/alamo-styles/cut-paper/tree.png",
    atmosphere: "paper",
    rollingGroundOffset: 22.81,
    flatHorizon: 62.83,
    treeRootOffset: 4.25,
  },
  {
    id: "grainy-editorial",
    label: "Grainy editorial",
    shortLabel: "Editorial",
    rollingSrc: "/alamo-styles/grainy-editorial/rolling.png",
    flatSrc: "/alamo-styles/grainy-editorial/flat.png",
    treeSrc: "/alamo-styles/grainy-editorial/tree.png",
    atmosphere: "grain",
    rollingGroundOffset: 10.17,
    flatHorizon: 64.72,
    treeRootOffset: -0.26,
  },
  {
    id: "lavender-dream",
    label: "Lavender dreamcloud",
    shortLabel: "Dreamcloud",
    rollingSrc: "/alamo-styles/lavender-dream/rolling.png",
    flatSrc: "/alamo-styles/lavender-dream/flat.png",
    treeSrc: "/alamo-styles/lavender-dream/tree.png",
    atmosphere: "dream",
    rollingGroundOffset: 9.49,
    flatHorizon: 57.33,
    treeRootOffset: -1.09,
  },
  {
    id: "airy-watercolor",
    label: "Airy watercolor",
    shortLabel: "Watercolor",
    rollingSrc: "/alamo-styles/airy-watercolor/rolling.png",
    flatSrc: "/alamo-styles/airy-watercolor/flat.png",
    treeSrc: "/alamo-styles/airy-watercolor/tree.png",
    atmosphere: "watercolor",
    rollingGroundOffset: 6.91,
    flatHorizon: 53.85,
    treeRootOffset: -0.33,
  },
  {
    id: "blue-duotone",
    label: "Monochrome blue",
    shortLabel: "Blue duotone",
    rollingSrc: "/alamo-styles/blue-duotone/rolling.png",
    flatSrc: "/alamo-styles/blue-duotone/flat.png",
    treeSrc: "/alamo-styles/blue-duotone/tree.png",
    atmosphere: "blue",
    rollingGroundOffset: 13.57,
    flatHorizon: 60.87,
    treeRootOffset: 0.69,
  },
  {
    id: "golden-hour",
    label: "Golden-hour painterly",
    shortLabel: "Golden hour",
    rollingSrc: "/alamo-styles/golden-hour/rolling.png",
    flatSrc: "/alamo-styles/golden-hour/flat.png",
    treeSrc: "/alamo-styles/golden-hour/tree.png",
    atmosphere: "golden",
    rollingGroundOffset: 6.31,
    flatHorizon: 71.01,
    treeRootOffset: -1.98,
  },
  {
    id: "vivid-surreal",
    label: "Vivid surreal",
    shortLabel: "Surreal",
    rollingSrc: "/alamo-styles/vivid-surreal/rolling.png",
    flatSrc: "/alamo-styles/vivid-surreal/flat.png",
    treeSrc: "/alamo-styles/vivid-surreal/tree.png",
    atmosphere: "surreal",
    rollingGroundOffset: 20.4,
    flatHorizon: 59.19,
    treeRootOffset: 0.08,
  },
  {
    id: "cinematic-glow",
    label: "Cinematic backlight",
    shortLabel: "Cinematic",
    rollingSrc: "/alamo-styles/cinematic-glow/rolling.png",
    flatSrc: "/alamo-styles/cinematic-glow/flat.png",
    treeSrc: "/alamo-styles/cinematic-glow/tree.png",
    atmosphere: "cinematic",
    rollingGroundOffset: 10.38,
    flatHorizon: 70.14,
    treeRootOffset: 0.35,
  },
  {
    id: "soft-daylight",
    label: "Soft daylight glints",
    shortLabel: "Soft daylight",
    rollingSrc: "/alamo-styles/soft-daylight/rolling.png",
    flatSrc: "/alamo-styles/soft-daylight/flat.png",
    treeSrc: "/alamo-styles/soft-daylight/tree.png",
    atmosphere: "glints",
    rollingGroundOffset: 11.69,
    flatHorizon: 75.96,
    treeRootOffset: 0.42,
  },
  {
    id: "voxel",
    label: "Voxel diorama",
    shortLabel: "Voxel",
    rollingSrc: "/alamo-styles/voxel/rolling.png",
    flatSrc: "/alamo-styles/voxel/flat.png",
    treeSrc: "/alamo-styles/voxel/tree.png",
    atmosphere: "voxel",
    rollingGroundOffset: 12.11,
    flatHorizon: 71.87,
    treeRootOffset: -1.84,
  },
  {
    id: "whiteboard",
    label: "Whiteboard marker",
    shortLabel: "Whiteboard",
    rollingSrc: "/alamo-styles/whiteboard/rolling.png",
    flatSrc: "/alamo-styles/whiteboard/flat.png",
    treeSrc: "/alamo-styles/whiteboard/tree.png",
    atmosphere: "whiteboard",
    rollingGroundOffset: 1.77,
    flatHorizon: 73.19,
    treeRootOffset: 0.42,
  },
  {
    id: "handmade-clay",
    label: "Handmade clay",
    shortLabel: "Clay",
    rollingSrc: "/alamo-styles/handmade-clay/rolling.png",
    flatSrc: "/alamo-styles/handmade-clay/flat.png",
    treeSrc: "/alamo-styles/handmade-clay/tree.png",
    atmosphere: "clay",
    rollingGroundOffset: 1.35,
    flatHorizon: 69.66,
    treeRootOffset: -1.43,
  },
] as const;

export type AlamoStyle = (typeof ALAMO_STYLES)[number]["id"];
export type AlamoStyleDefinition = (typeof ALAMO_STYLES)[number];

export const DEFAULT_ALAMO_STYLE: AlamoStyle = "control";

export function getAlamoStyle(style: AlamoStyle): AlamoStyleDefinition {
  return ALAMO_STYLES.find(({ id }) => id === style) ?? ALAMO_STYLES[0];
}
