export const ALAMO_STYLES = [
  {
    id: "control",
    label: "Current · control",
    shortLabel: "Control",
    rollingSrc: null,
    flatSrc: null,
    treeSrc: "/monterey-cypress.png",
    atmosphere: "control",
  },
  {
    id: "risograph",
    label: "Risograph print",
    shortLabel: "Risograph",
    rollingSrc: "/alamo-styles/risograph/rolling.png",
    flatSrc: "/alamo-styles/risograph/flat.png",
    treeSrc: "/alamo-styles/risograph/tree.png",
    atmosphere: "paper",
  },
  {
    id: "painterly-realism",
    label: "Restrained painterly",
    shortLabel: "Painterly",
    rollingSrc: "/alamo-styles/painterly-realism/rolling.png",
    flatSrc: "/alamo-styles/painterly-realism/flat.png",
    treeSrc: "/alamo-styles/painterly-realism/tree.png",
    atmosphere: "daylight",
  },
  {
    id: "ascii-terminal",
    label: "ASCII terminal garden",
    shortLabel: "ASCII",
    rollingSrc: "/alamo-styles/ascii-terminal/rolling.png",
    flatSrc: "/alamo-styles/ascii-terminal/flat.png",
    treeSrc: "/alamo-styles/ascii-terminal/tree.png",
    atmosphere: "terminal",
  },
  {
    id: "cut-paper",
    label: "Warm cut paper",
    shortLabel: "Cut paper",
    rollingSrc: "/alamo-styles/cut-paper/rolling.png",
    flatSrc: "/alamo-styles/cut-paper/flat.png",
    treeSrc: "/alamo-styles/cut-paper/tree.png",
    atmosphere: "paper",
  },
  {
    id: "grainy-editorial",
    label: "Grainy editorial",
    shortLabel: "Editorial",
    rollingSrc: "/alamo-styles/grainy-editorial/rolling.png",
    flatSrc: "/alamo-styles/grainy-editorial/flat.png",
    treeSrc: "/alamo-styles/grainy-editorial/tree.png",
    atmosphere: "grain",
  },
  {
    id: "lavender-dream",
    label: "Lavender dreamcloud",
    shortLabel: "Dreamcloud",
    rollingSrc: "/alamo-styles/lavender-dream/rolling.png",
    flatSrc: "/alamo-styles/lavender-dream/flat.png",
    treeSrc: "/alamo-styles/lavender-dream/tree.png",
    atmosphere: "dream",
  },
  {
    id: "airy-watercolor",
    label: "Airy watercolor",
    shortLabel: "Watercolor",
    rollingSrc: "/alamo-styles/airy-watercolor/rolling.png",
    flatSrc: "/alamo-styles/airy-watercolor/flat.png",
    treeSrc: "/alamo-styles/airy-watercolor/tree.png",
    atmosphere: "watercolor",
  },
  {
    id: "blue-duotone",
    label: "Monochrome blue",
    shortLabel: "Blue duotone",
    rollingSrc: "/alamo-styles/blue-duotone/rolling.png",
    flatSrc: "/alamo-styles/blue-duotone/flat.png",
    treeSrc: "/alamo-styles/blue-duotone/tree.png",
    atmosphere: "blue",
  },
  {
    id: "golden-hour",
    label: "Golden-hour painterly",
    shortLabel: "Golden hour",
    rollingSrc: "/alamo-styles/golden-hour/rolling.png",
    flatSrc: "/alamo-styles/golden-hour/flat.png",
    treeSrc: "/alamo-styles/golden-hour/tree.png",
    atmosphere: "golden",
  },
  {
    id: "vivid-surreal",
    label: "Vivid surreal",
    shortLabel: "Surreal",
    rollingSrc: "/alamo-styles/vivid-surreal/rolling.png",
    flatSrc: "/alamo-styles/vivid-surreal/flat.png",
    treeSrc: "/alamo-styles/vivid-surreal/tree.png",
    atmosphere: "surreal",
  },
  {
    id: "cinematic-glow",
    label: "Cinematic backlight",
    shortLabel: "Cinematic",
    rollingSrc: "/alamo-styles/cinematic-glow/rolling.png",
    flatSrc: "/alamo-styles/cinematic-glow/flat.png",
    treeSrc: "/alamo-styles/cinematic-glow/tree.png",
    atmosphere: "cinematic",
  },
  {
    id: "soft-daylight",
    label: "Soft daylight glints",
    shortLabel: "Soft daylight",
    rollingSrc: "/alamo-styles/soft-daylight/rolling.png",
    flatSrc: "/alamo-styles/soft-daylight/flat.png",
    treeSrc: "/alamo-styles/soft-daylight/tree.png",
    atmosphere: "glints",
  },
  {
    id: "voxel",
    label: "Voxel diorama",
    shortLabel: "Voxel",
    rollingSrc: "/alamo-styles/voxel/rolling.png",
    flatSrc: "/alamo-styles/voxel/flat.png",
    treeSrc: "/alamo-styles/voxel/tree.png",
    atmosphere: "voxel",
  },
  {
    id: "whiteboard",
    label: "Whiteboard marker",
    shortLabel: "Whiteboard",
    rollingSrc: "/alamo-styles/whiteboard/rolling.png",
    flatSrc: "/alamo-styles/whiteboard/flat.png",
    treeSrc: "/alamo-styles/whiteboard/tree.png",
    atmosphere: "whiteboard",
  },
  {
    id: "handmade-clay",
    label: "Handmade clay",
    shortLabel: "Clay",
    rollingSrc: "/alamo-styles/handmade-clay/rolling.png",
    flatSrc: "/alamo-styles/handmade-clay/flat.png",
    treeSrc: "/alamo-styles/handmade-clay/tree.png",
    atmosphere: "clay",
  },
] as const;

export type AlamoStyle = (typeof ALAMO_STYLES)[number]["id"];
export type AlamoStyleDefinition = (typeof ALAMO_STYLES)[number];

export const DEFAULT_ALAMO_STYLE: AlamoStyle = "control";

export function getAlamoStyle(style: AlamoStyle): AlamoStyleDefinition {
  return ALAMO_STYLES.find(({ id }) => id === style) ?? ALAMO_STYLES[0];
}
